version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql
volumes:
  db_data:
